package greycos.solver.core.preview.api.move.builtin;

import static org.assertj.core.api.Assertions.assertThat;
import static org.assertj.core.api.SoftAssertions.assertSoftly;

import java.util.List;

import greycos.solver.core.api.solver.SolutionManager;
import greycos.solver.core.preview.api.move.Move;
import greycos.solver.core.preview.api.neighborhood.test.NeighborhoodTester;
import greycos.solver.core.testcotwin.list.TestdataListEntity;
import greycos.solver.core.testcotwin.list.TestdataListSolution;
import greycos.solver.core.testcotwin.list.pinned.TestdataPinnedListEntity;
import greycos.solver.core.testcotwin.list.pinned.TestdataPinnedListSolution;
import greycos.solver.core.testcotwin.list.unassignedvar.TestdataAllowsUnassignedValuesListEntity;
import greycos.solver.core.testcotwin.list.unassignedvar.TestdataAllowsUnassignedValuesListSolution;
import greycos.solver.core.testcotwin.list.valuerange.TestdataListEntityProvidingEntity;
import greycos.solver.core.testcotwin.list.valuerange.TestdataListEntityProvidingSolution;
import greycos.solver.core.testcotwin.list.valuerange.unassignedvar.TestdataListUnassignedEntityProvidingEntity;
import greycos.solver.core.testcotwin.list.valuerange.unassignedvar.TestdataListUnassignedEntityProvidingSolution;

import org.jspecify.annotations.NullMarked;
import org.junit.jupiter.api.Test;

@NullMarked
class ListChangeMoveProviderTest {

  @Test
  void pinnedEntitySkipped() {
    var solutionMetaModel = TestdataPinnedListSolution.buildMetaModel();
    var variableMetaModel =
        solutionMetaModel.genuineEntity(TestdataPinnedListEntity.class).listVariable();

    var solution = TestdataPinnedListSolution.generateInitializedSolution(2, 2);
    solution.getEntityList().getFirst().setPinned(true);

    // Values can neither leave a pinned entity nor be moved into it.
    var moveList =
        NeighborhoodTester.build(new ListChangeMoveProvider<>(variableMetaModel), solutionMetaModel)
            .using(solution)
            .getMovesAsList();
    assertThat(moveList).isEmpty();
  }

  @Test
  void fromSolution() {
    var solutionMetaModel = TestdataListSolution.buildMetaModel();
    var variableMetaModel =
        solutionMetaModel.genuineEntity(TestdataListEntity.class).listVariable();

    var solution = TestdataListSolution.generateUninitializedSolution(2, 2);
    var e1 = solution.getEntityList().get(0);
    var e2 = solution.getEntityList().get(1);
    var initiallyAssignedValue = solution.getValueList().get(1);
    e2.getValueList().add(initiallyAssignedValue);
    SolutionManager.updateShadowVariables(solution);

    var moveList =
        NeighborhoodTester.build(new ListChangeMoveProvider<>(variableMetaModel), solutionMetaModel)
            .using(solution)
            .getMovesAsList();
    assertThat(moveList).hasSize(1);

    // Assign and unassign moves are generated by their dedicated providers.
    var move = getListChangeMove(moveList, 0);
    assertSoftly(
        softly -> {
          softly.assertThat(move.getSourceEntity()).isEqualTo(e2);
          softly.assertThat(move.getSourceIndex()).isZero();
          softly.assertThat(move.getDestinationEntity()).isEqualTo(e1);
          softly.assertThat(move.getDestinationIndex()).isZero();
          softly.assertThat(move.getPlanningEntities()).containsExactly(e2, e1);
          softly.assertThat(move.getPlanningValues()).containsExactly(initiallyAssignedValue);
        });
  }

  @Test
  void fromEntity() {
    var solutionMetaModel = TestdataListEntityProvidingSolution.buildMetaModel();
    var variableMetaModel =
        solutionMetaModel.genuineEntity(TestdataListEntityProvidingEntity.class).listVariable();

    var solution = TestdataListEntityProvidingSolution.generateSolution();
    var e1 = solution.getEntityList().getFirst();
    var v1 = solution.getValueList().getFirst();
    e1.getValueList().clear();
    var e2 = solution.getEntityList().get(1);
    e2.getValueList().add(e2.getValueRange().getFirst());
    SolutionManager.updateShadowVariables(solution);

    var moveList =
        NeighborhoodTester.build(new ListChangeMoveProvider<>(variableMetaModel), solutionMetaModel)
            .using(solution)
            .getMovesAsList();
    assertThat(moveList).hasSize(1);

    var move = getListChangeMove(moveList, 0);
    assertSoftly(
        softly -> {
          softly.assertThat(move.getSourceEntity()).isEqualTo(e2);
          softly.assertThat(move.getSourceIndex()).isZero();
          softly.assertThat(move.getDestinationEntity()).isEqualTo(e1);
          softly.assertThat(move.getDestinationIndex()).isZero();
          softly.assertThat(move.getPlanningEntities()).containsExactly(e2, e1);
          softly.assertThat(move.getPlanningValues()).containsExactly(v1);
        });
  }

  @Test
  void fromEntityAllowsUnassigned() {
    var solutionMetaModel = TestdataListUnassignedEntityProvidingSolution.buildMetaModel();
    var variableMetaModel =
        solutionMetaModel
            .genuineEntity(TestdataListUnassignedEntityProvidingEntity.class)
            .listVariable();

    var solution = TestdataListUnassignedEntityProvidingSolution.generateSolution();
    var e1 = solution.getEntityList().get(0);
    var e2 = solution.getEntityList().get(1);
    var v1 = solution.getValueList().getFirst();
    e2.getValueList().add(v1);

    var moveList =
        NeighborhoodTester.build(new ListChangeMoveProvider<>(variableMetaModel), solutionMetaModel)
            .using(solution)
            .getMovesAsList();
    assertThat(moveList).hasSize(1);

    var move = getListChangeMove(moveList, 0);
    assertSoftly(
        softly -> {
          softly.assertThat(move.getSourceEntity()).isEqualTo(e2);
          softly.assertThat(move.getSourceIndex()).isZero();
          softly.assertThat(move.getDestinationEntity()).isEqualTo(e1);
          softly.assertThat(move.getDestinationIndex()).isZero();
          softly.assertThat(move.getPlanningEntities()).containsExactly(e2, e1);
          softly.assertThat(move.getPlanningValues()).containsExactly(v1);
        });
  }

  @Test
  void fromSolutionAllowsUnassigned() {
    var solutionMetaModel = TestdataAllowsUnassignedValuesListSolution.buildMetaModel();
    var variableMetaModel =
        solutionMetaModel
            .genuineEntity(TestdataAllowsUnassignedValuesListEntity.class)
            .listVariable();
    var solution = TestdataAllowsUnassignedValuesListSolution.generateUninitializedSolution(2, 2);
    var e1 = solution.getEntityList().get(0);
    var e2 = solution.getEntityList().get(1);
    var v1 = solution.getValueList().getFirst();
    e2.getValueList().add(v1);
    SolutionManager.updateShadowVariables(solution);

    var moveList =
        NeighborhoodTester.build(new ListChangeMoveProvider<>(variableMetaModel), solutionMetaModel)
            .using(solution)
            .getMovesAsList();
    assertThat(moveList).hasSize(1);

    var move = getListChangeMove(moveList, 0);
    assertSoftly(
        softly -> {
          softly.assertThat(move.getSourceEntity()).isEqualTo(e2);
          softly.assertThat(move.getSourceIndex()).isZero();
          softly.assertThat(move.getDestinationEntity()).isEqualTo(e1);
          softly.assertThat(move.getDestinationIndex()).isZero();
          softly.assertThat(move.getPlanningEntities()).containsExactly(e2, e1);
          softly.assertThat(move.getPlanningValues()).containsExactly(v1);
        });
  }

  private static <Solution_, Entity_, Value_>
      ListChangeMove<Solution_, Entity_, Value_> getListChangeMove(
          List<Move<Solution_>> moveList, int index) {
    return (ListChangeMove<Solution_, Entity_, Value_>) moveList.get(index);
  }
}
