
== Main idea of this project

Reimplement nearby, multi-threaded incremental solving, partitioned search features by using OptaPlanner code (Apache 2.0)
inside fork of the latest version of Timefold Community Edition (Apache 2.0)
and implement fixes of bugs, described into release notes.

Additionally try to implement: enhanced node sharing, best solution events throttling and other enhancements of reimplemented features.

== Build from source

. Install JDK 17+ and Maven 3.9+, for example with https://sdkman.io[Sdkman]:
+
----
$ sdk install java
$ sdk install maven
----

. Git clone this repository:
+
----
$ git clone https://github.com/CameleoGrey/greycos-solver.git
$ cd greycos-solver
----

. Build it from source:
+
----
$ ./mvnw clean install -Dquickly
----

== Legal notice

Greycos Solver was forked on 21 December 2025 from Timefold Solver Community Edition,
which was entirely Apache-2.0 licensed (a permissive license).

Timefold Solver is a derivative work of OptaPlanner and OptaPy, which includes copyrights of 
the original creator, Red Hat Inc., affiliates, and contributors, that were all entirely 
licensed under the Apache-2.0 license. Every source file has been modified.
