
== Main idea of this project

Integrate back several advanced features from OptaPlanner (Apache 2.0) into fork of TimeFold Solver Community Edition (Apache 2.0).

Reinvent (create my own) implementations of advanced Timefold Solver features based on publicly available information (common public description without
access to the propritary codebase or byte code).

Implement some good ideas from my own GreyJack Solver (Apache 2.0).

== Build from source

. Install JDK 17+ and Maven 3.9+, for example with https://sdkman.io[Sdkman]:
+
----
$ sdk install java
$ sdk install maven
----

. Git clone this repository:
+
----
$ git clone https://github.com/CameleoGrey/greycos-solver.git
$ cd greycos-solver
----

. Build it from source:
+
----
$ ./mvnw clean install -Dquickly
----

== Legal notice

Greycos Solver was forked on 21 December 2025 from Timefold Solver Community Edition,
which was entirely Apache-2.0 licensed (a permissive license).

Timefold Solver is a derivative work of OptaPlanner and OptaPy, which includes copyrights of 
the original creator, Red Hat Inc., affiliates, and contributors, that were all entirely 
licensed under the Apache-2.0 license. Every source file has been modified.

I'd never buy the Enterprise Edition of TimeFold Solver and never had an access to its source code or its byte code.
