package ai.greycos.solver.core.impl.cotwin.common;

import ai.greycos.solver.core.api.cotwin.variable.PlanningVariable;

/**
 * Determines how members (fields and methods) of the cotwin (for example the {@link
 * PlanningVariable planner variable}) are accessed.
 */
public enum CotwinAccessType {
  /**
   * Determine what cotwin access type to use automatically.
   *
   * <p>This is the default.
   */
  AUTO,

  /**
   * Use reflection to read/write members (fields and methods) of the cotwin.
   *
   * <p>When used in a modulepath, the module must be open. When used in GraalVM, the cotwin must be
   * open for reflection.
   */
  FORCE_REFLECTION,

  /**
   * Use Gizmo generated bytecode to access members (fields and methods) to avoid reflection for
   * additional performance.
   *
   * <p>This is the default when the application is run inside a JVM and not a native image.
   */
  FORCE_GIZMO
}
