[#backwardsCompatibility]
= Backwards compatibility
:doctype: book
:icons: font

GreyCOS Solver separates its API from its implementation:

* **Public API**: All classes under these `api` and `config` namespaces are 100% *backwards compatible* in future minor and hotfix releases:
** `ai.greycos.solver.core.api`
** `ai.greycos.solver.benchmark.api`
** `ai.greycos.solver.*.api`
** `ai.greycos.solver.core.config`
** `ai.greycos.solver.benchmark.config`
* **Implementation classes**: All other classes are _not_ backwards compatible.
They will change in future major or minor releases,
but probably not in hotfix releases.

Backwards incompatible changes for a new major version are clearly documented in xref:upgrading-greycos-solver/upgrade-to-latest-version.adoc#manualUpgrade[the upgrade recipe].


[#previewFeatures]
== Preview features

GreyCOS Solver includes several components which are only available as preview features.
We use preview features as means of sharing our work with the community early
and to get feedback on how to develop them further,
without being hamstrung by our strict backwards compatibility guarantees.

We deliver preview features to the same standard of quality as the rest of GreyCOS Solver.
However, their APIs and behavior are not yet considered stable, pending user feedback.
Any class, method or field related to these features may change or be removed without prior notice,
although we strive to avoid this as much as possible.

Preview features need to be activated in the solverConfig.xml file.

[source,xml,options="nowrap"]
----
<solver xmlns="https://greycos.ai/xsd/solver">
  <enablePreviewFeature>DIVERSIFIED_LATE_ACCEPTANCE</enablePreviewFeature>
  <enablePreviewFeature>PLANNING_SOLUTION_DIFF</enablePreviewFeature>
</solver>
----

Preview features often live in the `preview.api` package, and they are:

- xref:optimization-algorithms/local-search.adoc#diversifiedLateAcceptance[Diversified Late Acceptance] acceptor,
- xref:constraints-and-score/understanding-the-score.adoc#solutionDiff[Solution diff API]
in the `ai.greycos.solver.core.preview.api.cotwin.solution.diff` package and in the `SolutionManager`,
- Neighborhoods API.

We encourage you to try these preview features and give us feedback on your experience with them.
Please direct your feedback to
https://github.com/CameleoGrey/greycos-solver[GreyCOS Solver GitHub]
