[#upgradeFromOptaPlanner]
= Upgrade from OptaPlanner
:page-aliases: upgrade-and-migration/migrate-from-optaplanner.adoc
:doctype: book
:sectnums:
:icons: font

In spring of 2024, Red Hat announced https://access.redhat.com/articles/7060671[end of life for OptaPlanner].
Greycos Solver is a faster, feature-rich, and actively developed fork of OptaPlanner by the same team.

== Automatic upgrade

Upgrading from OptaPlanner to Greycos Solver only takes two minutes.
Run the command below to upgrade your java, build and other code automatically.

[tabs]
====
Maven::
+
--
[source,shell,subs=attributes+]
----
mvn org.openrewrite.maven:rewrite-maven-plugin:{rewrite-maven-plugin-version}:run -Drewrite.recipeArtifactCoordinates=ai.greycos.solver:greycos-solver-migration:{greycos-solver-version} -Drewrite.activeRecipes=ai.greycos.solver.migration.ToLatest
----
--

Gradle::
+
--
[source,shell,subs=attributes+]
----
curl https://raw.githubusercontent.com/CameleoGrey/greycos-solver/refs/tags/v{greycos-solver-version}/migration/upgrade-greycos.gradle > upgrade-greycos.gradle ; gradle -Dorg.gradle.jvmargs=-Xmx2G --init-script upgrade-greycos.gradle rewriteRun -DgreycosSolverVersion={greycos-solver-version} ; rm upgrade-greycos.gradle
----
--
====

include::framework-version-warning.adoc[leveloffset=+1]

Having done that, do a test run of the solver and commit the changes.
If it doesn't work, just revert it instead and
https://github.com/greycosai/greycos-solver/issues[submit an issue].
We'll fix it with the highest priority.

Greycos Solver 1.x does not support `scoreDRL`, nor is it upgraded automatically.
If you're still using `scoreDRL` from OptaPlanner 7.x,
please link:https://greycos.ai/blog/migrating-score-drl-to-constraint-streams[upgrade to Constraint Streams first].

== Manual upgrade

Greycos Solver 1.x is backward compatible with OptaPlanner 8.x,
except for the following changes:

* Minimum Java 17 (LTS). Java 21 (LTS) and the latest Java version are also supported.
* The Maven/Gradle GAVs changed:
** The groupId changed from `org.optaplanner` to `ai.greycos.solver`.
** The artifactIds changed from `optaplanner-\*` to `greycos-solver-*`.
** ArtifactIds containing `peristence-` changed from `optaplanner-persistence-\*` to `greycos-solver-*`.
*** For example, `optaplanner-persistence-jackson` changed to `greycos-solver-jackson`.
* The import statements changed accordingly:
** `import org.optaplanner...;` changed to `import ai.greycos.solver...;`.
** `import org.optaplanner.persistence...;` changed to `import ai.greycos.solver...;` too.
* The JEE dependencies changed from `javax` to `jakarta` to accommodate Spring 3 and Quarkus 3.
** This is the same difference as between OptaPlanner 8.x and OptaPlanner 9.x.
* The `OptaPlannerJacksonModule` class is now called `GreycosJacksonModule`.
* The deprecated `scoreDRL` support is removed, because Drools with its transitive dependencies have been removed entirely.
* The unsecure module `persistence-xstream` is removed, because of old, unresolved CVEs in XStream.
* The deprecated, undocumented `ScoreHibernateType` has been removed because of Jakarta.
Use JPA's `ScoreConverter` instead.
