package ai.greycos.solver.core.api.cotwin.valuerange;

import java.util.Collection;
import java.util.Iterator;
import java.util.List;
import java.util.Set;
import java.util.random.RandomGenerator;

import ai.greycos.solver.core.api.cotwin.variable.PlanningListVariable;
import ai.greycos.solver.core.api.cotwin.variable.PlanningVariable;

import org.jspecify.annotations.NullMarked;
import org.jspecify.annotations.Nullable;

/**
 * A ValueRange is a set of a values for a {@link PlanningVariable} or {@link PlanningListVariable}.
 * These values might be stored in memory as a {@link Collection} (usually a {@link List} or {@link
 * Set}), but if the values are numbers, they can also be stored in memory by their bounds to use
 * less memory and provide more opportunities.
 *
 * <p>ValueRange is stateless, and its contents must not depend on any planning variables.
 * Implementations must be immutable.
 *
 * <p>It is recommended to implement {@link Object#equals(Object)} and {@link Object#hashCode()} and
 * for those implementations to be efficient, because instances are often cached.
 *
 * <p>Don't implement this interface directly. If you can't use a collection to store the values,
 * use {@link ValueRangeFactory} to get an instance of a {@link ValueRange}.
 *
 * @see ValueRangeProvider
 * @see ValueRangeFactory
 */
@NullMarked
public interface ValueRange<T> {

  /**
   * This must be consistent with {@link #getSize()}.
   *
   * @return true if the range is empty
   */
  boolean isEmpty();

  /**
   * @param value sometimes null
   * @return true if the range contains that value
   */
  boolean contains(@Nullable T value);

  /**
   * Used by uniform random selection.
   *
   * @return the exact number of elements generated by this {@link ValueRange}, always {@code >= 0}
   */
  long getSize();

  /**
   * Used by uniform random selection.
   *
   * @param index always {@code <} {@link #getSize()}
   * @return sometimes null (if {@link PlanningVariable#allowsUnassigned()} is true)
   */
  @Nullable T get(long index);

  /** Select the elements in original (natural) order. */
  Iterator<T> createOriginalIterator();

  /**
   * Select in random order, but without shuffling the elements. Each element might be selected
   * multiple times. Scales well because it does not require caching.
   *
   * @param workingRandom the {@link RandomGenerator} to use when any random number is needed, so
   *     runs are reproducible.
   */
  Iterator<T> createRandomIterator(RandomGenerator workingRandom);
}
